from pkg_resources import resource_filename

RU_MODEL_CONFIG = resource_filename(__name__, "models/ru_model.yaml")
RU_MODEL_WEIGHTS = resource_filename(__name__, "models/ru_model.h5")
RU_GRAMMEMES_DICT_INPUT = resource_filename(__name__, "models/ru_gram_input.json")
RU_GRAMMEMES_DICT_OUTPUT = resource_filename(__name__, "models/ru_gram_output.json")
RU_WORD_VOCABULARY = resource_filename(__name__, "models/ru_word_vocabulary.pickle")
RU_CHAR_SET = resource_filename(__name__, "models/ru_char_set.txt")
RU_CHAR_MODEL_CONFIG = resource_filename(__name__, "models/ru_char_model.yaml")
RU_CHAR_MODEL_WEIGHTS = resource_filename(__name__, "models/ru_char_model.h5")
RU_BUILD_CONFIG = resource_filename(__name__, "models/ru_build_config.json")
RU_TRAIN_CONFIG = resource_filename(__name__, "models/ru_train_config.json")

TEST_TAGGED_FOLDER = resource_filename(__name__, "test/tagged")
TEST_UNTAGGED_VK = resource_filename(__name__, "test/untagged/VK_extracted.txt")
TEST_UNTAGGED_LENTA = resource_filename(__name__, "test/untagged/Lenta_extracted.txt")
TEST_UNTAGGED_JZ = resource_filename(__name__, "test/untagged/JZ_extracted.txt")
TEST_TAGGED_VK = resource_filename(__name__, "test/tagged/VK_extracted.txt")
TEST_TAGGED_LENTA = resource_filename(__name__, "test/tagged/Lenta_extracted.txt")
TEST_TAGGED_JZ = resource_filename(__name__, "test/tagged/JZ_extracted.txt")
TEST_GOLD_VK = resource_filename(__name__, "test/gold/VK_gold.txt")
TEST_GOLD_LENTA = resource_filename(__name__, "test/gold/Lenta_gold.txt")
TEST_GOLD_JZ = resource_filename(__name__, "test/gold/JZ_gold.txt")